version: '3'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
    networks:
      - micro-app
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - "mongodata:/data/db"
    networks:
      - micro-app

volumes:
  mongodata:

networks:
  micro-app: